apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany
  StorageClassName: my-azurefile-sc
  resouorces:
    requests:
      storage: 5Gi