apiVersion: v1
kind: Service 
metadata:
  name: frontend-ngnixapp-loadbalancer-service
  labels:
    app: frontend-ngnixapp
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend-ngnixapp
  ports: 
    - name: http
      port: 80
      targetPort: 80