apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp2-rs
spec:
  replicas: 3
  selector:
    matchLabels:

  template:
    metadata:
      name: myapp2-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: stacksimplify/kubenginx:1.0.0
          ports: 
            - containerPort: 80
        
    